development:
  adapter: postgresql
  database: stringer_dev
  encoding: unicode
  pool: 5

test:
  adapter: sqlite3
  database: db/stringer_test.sqlite

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['STRINGER_DATABASE'] || "stringer" %>
  username: <%= ENV['STRINGER_DATABASE_USERNAME'] %>
  password: <%= ENV['STRINGER_DATABASE_PASSWORD'] %>
  host: <%= ENV['STRINGER_DATABASE_HOST'] %>
  port: <%= ENV['STRINGER_DATABASE_PORT'] %>
